### ISSUE TITLE
tumblr.py执行时报错'module' object has no attribute 'SIGBUS'

### ISSUE THREAD

**Issue by Richeir** [PeterDing/iScript#108]
$ python /d/GitHub/iScript/tumblr.py
Traceback (most recent call last):
  File "D:/GitHub/iScript/tumblr.py", line 617, in <module>
    main(argv)
  File "D:/GitHub/iScript/tumblr.py", line 554, in main
    handle_signal()
  File "D:/GitHub/iScript/tumblr.py", line 539, in handle_signal
    signal.signal(signal.SIGBUS, sighandler)
AttributeError: 'module' object has no attribute 'SIGBUS'

新手求解

**Comment by Richeir** [comment]
已经解决，需要在babun中运行
