### ISSUE TITLE
pan.baidu.com.py 上传文件报错

### ISSUE THREAD

**Issue by asuna** [PeterDing/iScript#115]
上传文件出现如下错误，CentOS 6.9，Python 2.7.13
前段时间使用一切正常，但是最近上传的时候总是报错
````bash
[root@tserver Downloads]# baidu u BDrip_Hayate_no_Gotoku-Moozzi2.md5 /
Traceback (most recent call last):
  File "/opt/iScript/pan.baidu.com.py", line 3610, in <module>
    main(argv)
  File "/opt/iScript/pan.baidu.com.py", line 3606, in main
    handle_command(comd, xxx)
  File "/opt/iScript/pan.baidu.com.py", line 3208, in handle_command
    px.upload(xxx[:-1], xxx[-1])
  File "/opt/iScript/pan.baidu.com.py", line 1458, in upload
    upload_datas = pk.load(f)
TypeError: ("'str' object is not callable", 'upload_function', ([],))
````

**Comment by asuna** [comment]
尝试删除~/.bp.pickle后解决了...
> rm -f ~/.bp.pickle
