### ISSUE TITLE
百度网盘登陆报错

### ISSUE THREAD

**Issue by hulvyou** [PeterDing/iScript#117]
-- check_login fail

  login failes
----------------------------------
! Error 120021: 登录失败,重新登录

两种报错

**Comment by nuomi1** [comment]
临时解决方案：使用 Chrome 隐身模式登录百度网盘，获取 Cookie。

**Comment by hulvyou** [comment]
@nuomi1 请问百度云盘不打开播放的前提下，可以获取到视频播放时长吗？

**Comment by nuomi1** [comment]
@hulvyou 网页？官方（Windows、macOS 等）客户端？这个脚本？

**Comment by hulvyou** [comment]
@nuomi1 用的是您这个脚本pan.baidu.com.py 可以获取到视频播放时长吗？
同时在使用转存别人分享的时候出现了如下错误
Traceback (most recent call last):
  File "pan.baidu.com.py", line 3610, in <module>
    main(argv)
  File "pan.baidu.com.py", line 3606, in main
    handle_command(comd, xxx)
  File "pan.baidu.com.py", line 3316, in handle_command
    url = re.search(r'(http://.+?.baidu.com/.+?)(#|$)', xxx[0]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by PeterDing** [comment]
@hulvyou 
把要转存的链接的 `https` 换成 `http`。

脚步无法获取视频时长。

**Comment by hulvyou** [comment]
@PeterDing 非常感谢，请问脚本下载文件的时候可以指定存放本地目录吗

**Comment by PeterDing** [comment]
@hulvyou 不可以，下载文件(文件夹)保存在运行脚本的当前目录。
