### ISSUE TITLE
tumblr 脚本无法打开新线程

### ISSUE THREAD

**Issue by Zardinality** [PeterDing/iScript#130]
```
INFO:
D = Downloads, R = Repair_Need
C = Completion, NE = Net_Errors, O = Offset
D: 0, R: 0, C: 0, NE: 0, O: 0 Traceback (most recent call last):
  File "/opt/home/admin/tumblr/tumblr.py", line 617, in <module>
    main(argv)
  File "/opt/home/admin/tumblr/tumblr.py", line 600, in main
    queue.put(item)
  File "/opt/lib/python2.7/multiprocessing/queues.py", line 320, in put
    self._start_thread()
  File "/opt/lib/python2.7/multiprocessing/queues.py", line 195, in _start_thread
    self._thread.start()
  File "/opt/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```
是在路由器上跑的，openwrt 改的 padavan，不知道有没有关系？当前的线程数很正常，也把线程限制调到了十万。

**Comment by PeterDing** [comment]
@Zardinality 没在 openwrt 上玩过，也不知道怎么跟你调。。。抱歉

**Comment by Zardinality** [comment]
@PeterDing 谢谢，维护这个 repo 想必很不容易

**Comment by Zardinality** [comment]
解决了，事先 `export -n LD_LIBRARY_PATH` 一下就好了。
