### ISSUE TITLE
百度盘上传好像不行

### ISSUE THREAD

**Issue by josephzjw** [PeterDing/iScript#132]
|-- upload_function: _rapidupload_file
Traceback (most recent call last):
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 3610, in <module>
    main(argv)
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 3606, in main
    handle_command(comd, xxx)
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 3208, in handle_command
    px.upload(xxx[:-1], xxx[-1])
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 1477, in upload
    self._upload_dir(lpath, rpath)
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 1439, in _upload_dir
    self._upload_file(localpath, remotepath)
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 1397, in _upload_file
    result = self._rapidupload_file(lpath, rpath)
  File "/home/xxx/my-project/iScript/pan.baidu.com.py", line 1141, in _rapidupload_file
    r = ss.post(url, params=p, data=data, verify=VERIFY)
  File "/home/xxx/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/xxx/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xxx/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/xxx/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='c.pcs.baidu.com', port=443): Max retries exceeded with url: /rest/2.0/pcs/file?BDUSS=hYMlJPbHZLNUlNZ3VJZ0dpWXdoZzlLbWVaa1hJM0p1U3luOU42fmQzb2tkT2hhQVFBQUFBJCQAAAAAAAAAAAEAAAAgguoEc3VubnlyYWluXwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTnwFok58BabT&method=rapidupload&app_id=250528 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f73c9ca5450>: Failed to establish a new connection: [Errno 110] Connection timed out',))
显示这个错误。。。

**Comment by PeterDing** [comment]
@josephzjw 不要把 BDUSS 公开，不然，你网盘的内容就暴露了

**Comment by PeterDing** [comment]
@josephzjw 这个错(`Failed to establish a new connection: [Errno 110] Connection timed out`) 应该是你网络的问题或者是 百度服务器的问题。

**Comment by josephzjw** [comment]
好的，我知道了，谢谢啦
