### ISSUE TITLE
执行git clone过来，执行任何参数都会提示格式错误（行数507）

### ISSUE THREAD

**Issue by realercheng** [PeterDing/iScript#157]
$ python3 pan.baidu.com.py d "https://pan.baidu.com/s/15FA0l6fMfyHfFV4sDyfwPA" -s rr7o
  File "pan.baidu.com.py", line 507
    print s% (1, 93, '  !! you don\'t install shadowsocks for python2.')
          ^
SyntaxError: invalid syntax

**Comment by PeterDing** [comment]
@realercheng pan.baidu.com.py 是 python2 脚本。用 pip2 安装依赖后，用 python2 执行。

**Comment by realercheng** [comment]
使用python2执行报了另外一个错误，用的系统是CentOS 7.8：
=======================
$ ./pan.baidu.com.py login
Traceback (most recent call last):
  File "./pan.baidu.com.py", line 22, in <module>
    import rsa
  File "/usr/lib/python2.7/site-packages/rsa/__init__.py", line 24, in <module>
    from rsa.key import newkeys, PrivateKey, PublicKey
  File "/usr/lib/python2.7/site-packages/rsa/key.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file /usr/lib/python2.7/site-packages/rsa/key.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by PeterDing** [comment]
@realercheng 最新的 [rsa](https://github.com/sybrenstuvel/python-rsa/tree/master/rsa) 包没有 `rsa/init.py`。你可能需要用 `pip2 install rsa --upgrade` 升级到最新版本。
