### ISSUE TITLE
中断下载后重新下载出现解析错误

### ISSUE THREAD

**Issue by 0cean** [PeterDing/iScript#17]
LaN-DiskStation> Traceback (most recent call last):
  File "/volume1/homes/iScript/115.py", line 482, in <module>
    main(argv)
  File "/volume1/homes/iScript/115.py", line 474, in main
    x.get_infos(cid)
  File "/volume1/homes/iScript/115.py", line 189, in get_infos
    j = ss.get(url, params=params).json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 451, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 405, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.decoder.JSONDecodeError: Extra data: line 1 column 2090 - line 2 column 1 (char 2090 - 2095)

尝试过重装Python ，更换ip地址都是这个错误。

**Comment by PeterDing** [comment]
@0cean 
我这里正常。
你给出的结果显示json解析出错，你可以重装requests和simplejson试试。

**Comment by 0cean** [comment]
requests和simplejson都重装过，甚至换了一台电脑，在新的python环境也是这个错误，猜测我的账号可能被系统判定异常了，导致解析页面不是正常页面。

**Comment by PeterDing** [comment]
@0cean 我也遇到了这个问题，是登录过期导致的，重新登录就好。

**Comment by 0cean** [comment]
发现有时候重新登录就好了，但有时候重新登录后问题依旧。

**Comment by PeterDing** [comment]
@0cean 也许是115服务器的问题。我测试了很多次，这种情况发生频率很小。
