### ISSUE TITLE
pan.baidu 上传出现某些异常的时候，已上传list会丢失

### ISSUE THREAD

**Issue by goodbest** [PeterDing/iScript#20]
有时候因为连接问题，上传会出错，出现异常。这也属于正常现象。

不过这个时候记录的已上传的文件列表是不完整的。
再次运行的时候某些已经被上传的文件会重新被传一次。

```
Traceback (most recent call last):
  File "pan.baidu.com.py", line 3016, in <module>
    main(argv)
  File "pan.baidu.com.py", line 2695, in main
    px.upload(xxx[:-1], xxx[-1])
  File "pan.baidu.com.py", line 1167, in upload
    self._upload_dir(lpath, rpath)
  File "pan.baidu.com.py", line 1141, in _upload_dir
    self._upload_file(localpath, remotepath)
  File "pan.baidu.com.py", line 1099, in _upload_file
    result = self._rapidupload_file(lpath, rpath)
  File "pan.baidu.com.py", line 878, in _rapidupload_file
    r = ss.post(url, params=p, data=data, verify=VERIFY)
  File "/Library/Python/2.7/site-packages/requests-2.5.3-py2.7.egg/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.3-py2.7.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.3-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.3-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by PeterDing** [comment]
你可以用 -t e (检查云端同路径文件是否存在，如果存在则不上传。)

**Comment by goodbest** [comment]
这的确是一个解决方法
