### ISSUE TITLE
pan.baidu.com在upload的时候，有时候会碰到错误，然后就再也无法上传了

### ISSUE THREAD

**Issue by gfd6th** [PeterDing/iScript#39]
错误信息：

Traceback (most recent call last):
  File "/root/iScript/pan.baidu.com.py", line 3477, in <module>
    main(argv)
  File "/root/iScript/pan.baidu.com.py", line 3473, in main
    handle_command(comd, xxx)
  File "/root/iScript/pan.baidu.com.py", line 3084, in handle_command
    px.upload(xxx[:-1], xxx[-1])
  File "/root/iScript/pan.baidu.com.py", line 1358, in upload
    upload_datas = pk.load(f)
ValueError: insecure string pickle

**Comment by PeterDing** [comment]
把 ~/.bp.pickle 删了，再试试。

**Comment by gfd6th** [comment]
可以解决问题
