### ISSUE TITLE
虾米重复要求登陆

### ISSUE THREAD

**Issue by jjhhh464** [PeterDing/iScript#40]
我在国外的VPS里运行xiami.py
但是我登陆之后一运行python xiami.py d *****就又要求我登陆 please login
另外 我是虾米会员了 在国外可以使用

所以请问一下这是怎么回事？谢谢！

贴上信息：
运行环境：Ubuntu 14.04 x86_64
root@localhost:~/muu# python xiami.py login ** **
  -- login
  ++ login succeeds.
root@localhost:~/muu# python xiami.py d http://www.xiami.com/collect/114900095?spm=a1z1s.6843761.1478643745.3.Hm7SKv
  please login
root@localhost:~/muu# python xiami.py login ** **
  -- login
  ++ login succeeds.
root@localhost:~/muu# python xiami.py d http://www.xiami.com/album/2100181986?spm=a1z1s.6843761.1478643713.8.LJI4m0
  please login
root@localhost:~/muu#

**Comment by PeterDing** [comment]
我没国外的vps无法跟你测试。
但是我在本地运行是没有问题的。

你可以把 ~/.Xiami.cookies 删除试试。
如果你用taobao且能查 cookie，看看[这](https://github.com/PeterDing/iScript#3-用法)。

**Comment by jjhhh464** [comment]
我VPS没有安装图像界面（带不起来），没办法用浏览器了
我把本地机器运行过的的Xiami.cookies上传到VPS，虽然不提示login了
但是提示：
root@localhost:~/muu# python xiami.py d **URL
Traceback (most recent call last):
  File "xiami.py", line 1152, in <module>
    main(argv)
  File "xiami.py", line 1132, in main
    x.url_parser(urls)
  File "xiami.py", line 406, in url_parser
    self.download_collect()
  File "xiami.py", line 664, in download_collect
    if not args.play else ''
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-22: ordinal not in range(128)
root@localhost:~/muu#
算了，以后再研究了
谢谢你的回答
另外，这个你写的这个脚本很好用，再次感谢！ : )
