### ISSUE TITLE
baidupan经常出现以下错误

### ISSUE THREAD

**Issue by gfd6th** [PeterDing/iScript#44]
```python
Traceback (most recent call last):
  File "/root/iScript/pan.baidu.com.py", line 3477, in <module>
    main(argv)
  File "/root/iScript/pan.baidu.com.py", line 3473, in main
    handle_command(comd, xxx)
  File "/root/iScript/pan.baidu.com.py", line 3084, in handle_command
    px.upload(xxx[:-1], xxx[-1])
  File "/root/iScript/pan.baidu.com.py", line 1377, in upload
    self._upload_dir(lpath, rpath)
  File "/root/iScript/pan.baidu.com.py", line 1339, in _upload_dir
    self._upload_file(localpath, remotepath)
  File "/root/iScript/pan.baidu.com.py", line 1245, in _upload_file
    result = self._upload_slice(piece=piece, slice=slice)
  File "/root/iScript/pan.baidu.com.py", line 1130, in _upload_slice
    r = ss.post(url, params=p, data=data, verify=VERIFY, headers=theaders)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by PeterDing** [comment]
应该是你那里的网络出错
