### ISSUE TITLE
最近出现的错误...

### ISSUE THREAD

**Issue by asuna** [PeterDing/iScript#45]
baidu d http://pan.baidu.com/s/1c0uNupi -s fr78 -a10

````bash
Traceback (most recent call last):
  File "/root/iScript/pan.baidu.com.py", line 3477, in <module>
    main(argv)
  File "/root/iScript/pan.baidu.com.py", line 3473, in main
    handle_command(comd, xxx)
  File "/root/iScript/pan.baidu.com.py", line 3153, in handle_command
    xw.do(paths3)
  File "/root/iScript/pan.baidu.com.py", line 2879, in do
    self.get_params(path)
  File "/root/iScript/pan.baidu.com.py", line 2802, in get_params
    info = self.get_web_fileinfo(html, path)
  File "/root/iScript/pan.baidu.com.py", line 2789, in get_web_fileinfo
    info['uk']       = re.search(r'yunData\.MYUK = "(\d+)"', cm).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
````

**Comment by PeterDing** [comment]
登录后打开这个链接是存在的，
非登录，打开这个链接是不存在的，
应该是百度改分享策略了。

**Comment by darkrazer** [comment]
好棒的脚本，原来一直用的很好，不过从昨天开始就一直登陆失败，失败原因一直是 ! Error 120021 请问是百度改了什么东西么？还是我自己环境的问题？谢谢！
