### ISSUE TITLE
解析失败，怎么回事

### ISSUE THREAD

**Issue by panzhengyu** [PeterDing/iScript#54]
[root@panzhengyu ~]# python 91porn.py http://91porn.com/view_video.php?viewkey=ca773041172945155285

  ++ 正在下载: /root/ca773041172945155285.mp4
--2016-01-31 07:16:22--  http://[http://d.3p7.us/mp4hd/146126.mp4?st=1xwm0_uhrknngqzsbcqasw&e=1454249888]/
Resolving http://d.3p7.us/mp4hd/146126.mp4?st=1xwm0_uhrknngqzsbcqasw&e=1454249888... failed: Name or service not known.
wget: unable to resolve host address `http://d.3p7.us/mp4hd/146126.mp4?st=1xwm0_uhrknngqzsbcqasw&e=1454249888'

 ----###   ERROR ==> 1024 (Network failure.)   ###--- 

  ===>  wget -c -O "/root/ca773041172945155285.mp4.tmp" --header "User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.77 Safari/537.36" --header "Cookie: __cfduid=d309e849203892dc0ee241175c6dfd9ee1454242582; CLIPSHARE=b5q6psdkev3aroitg69fo9i3l6; watch_times=1" "http%3A%2F%2Fd.3p7.us%2Fmp4hd%2F146126.mp4%3Fst%3D1xWM0_UhRkNNGQzsBCqaSw%26e%3D1454249888"

**Comment by wangx2** [comment]
我也是解析失败，可能是网站升级了。

**Comment by ky0ncheng** [comment]
tumblr.py


Traceback (most recent call last):
  File "tumblr.py", line 617, in <module>
    main(argv)
  File "tumblr.py", line 575, in main
    tumblr = Tumblr(args, url)
  File "tumblr.py", line 287, in __init__
    self.make_items = self.parse_urls(url)
  File "tumblr.py", line 475, in parse_urls
    return self.download_photos(base_hostname, post_id=post_id, tag=self.args.tag)
  File "tumblr.py", line 427, in download_photos
    return self.download_photos_by_offset(base_hostname, post_id=post_id)
  File "tumblr.py", line 343, in download_photos_by_offset
    self.init_infos(base_hostname, 'photos')
  File "tumblr.py", line 298, in init_infos
    json_path = os.path.join(dir_, 'json.json')
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 13: ordinal not in range(128)

**Comment by nuomi1** [comment]
@ky0ncheng `UnicodeDecodeError` 什么系统？example 呢？

**Comment by ky0ncheng** [comment]
@nuomi1 okay,fixed~

ubuntu的奇葩问题
