### ISSUE TITLE
成功登录之后，运行python xiami.py d http://www.xiami.com/song/152453 报错

### ISSUE THREAD

**Issue by evindu** [PeterDing/iScript#72]
Traceback (most recent call last):
  File "xiami.py", line 1169, in <module>
    main(argv)
  File "xiami.py", line 1149, in main
    x.url_parser(urls)
  File "xiami.py", line 456, in url_parser
    self.download_song()
  File "xiami.py", line 644, in download_song
    songs = self.get_song(self.song_id)
  File "xiami.py", line 640, in get_song
    songs = self.get_songs(album_id, song_id=song_id)
  File "xiami.py", line 589, in get_songs
    song_info['song_played'] = song_played[i]
IndexError: list index out of range

**Comment by PeterDing** [comment]
修了一些 bug，再试试。
