### ISSUE TITLE
tumblr 貌似不能用了最近

### ISSUE THREAD

**Issue by guoweijia0579** [PeterDing/iScript#75]
tumblr 貌似不能用了最近，之前还是好好的

Traceback (most recent call last):
  File "./tumblr.py", line 617, in <module>
    main(argv)
  File "./tumblr.py", line 578, in main
    items = tumblr.get_item_generator()
  File "./tumblr.py", line 479, in get_item_generator
    items = self.make_items()
  File "./tumblr.py", line 347, in do
    base_hostname, offset=self.offset if not post_id else '', post_id=post_id)
  File "./tumblr.py", line 215, in _photo
    raw_data = self._request(base_hostname, 'posts', 'photo', params)
  File "./tumblr.py", line 180, in _request
    raise Error(s % (1, 91, json_data['meta']['msg']))
__main__.Error: Limit Exceeded

有人知道是什么意思么？
该代码在CENTOS 7 上运行，服务器在美国.

**Comment by yustarg** [comment]
我也遇到同样的问题，貌似是短时间内访问tumblr太多次，不知道peter是否有办法

**Comment by jackond** [comment]
也遇到这个问题了

**Comment by PeterDing** [comment]
应该是一个ip用一个api-key短时间内多次访问会被限制, 你们可以换一个 api-key 试试，[搜](https://github.com/search?p=2&q=tumblr+api+key&type=Code&utf8=%E2%9C%93)

也可以自己去 tumblr 注册一个 api-key

**Comment by kld123509945** [comment]
Hi, 我注册了api-key，请问怎么在tumblr.py中更换这个key呀？
我已经把signalAPI_KEY = ''中的字段换成我自己的OAuth 使用者键值。
然后提示line 14: `import argparse'  
谢谢！
