### ISSUE TITLE
win7 tumblr.py 报错

### ISSUE THREAD

**Issue by yustarg** [PeterDing/iScript#82]
Traceback (most recent call last):
  File "E:/Git/iScript/tumblr.py", line 617, in <module>
    main(argv)
  File "E:/Git/iScript/tumblr.py", line 554, in main
    handle_signal()
  File "E:/Git/iScript/tumblr.py", line 539, in handle_signal
    signal.signal(signal.SIGBUS, sighandler)
AttributeError: 'module' object has no attribute 'SIGBUS'

依赖都已安装，不知道为什么报这个错

**Comment by yustarg** [comment]
原来需要把这些包考到badun内置的python里，ok了，谢谢！

**Comment by nolatiy** [comment]
> 原来需要把这些包考到badun内置的python里，ok了，谢谢！

拷贝到哪里呀？我已经放进去了，为嘛还是No module named requests
