### ISSUE TITLE
win10 Tumblr.py 报错提示

### ISSUE THREAD

**Issue by Lugic1993** [PeterDing/iScript#85]
报错提示如下
0 [main] python2.7 15548 child_info_fork::abort: unable to remap datetime.dll to same address as parent (0x1010000) - try running rebaseall
Traceback (most recent call last):
  File "/home/Lugic/iScript/tumblr.py", line 617, in <module>
    main(argv)
  File "/home/Lugic/iScript/tumblr.py", line 565, in main
    thr.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable

此时已经开启了VPN，且tumblr可以正常登陆

**Comment by PeterDing** [comment]
这是在什么终端发生的

**Comment by Lugic1993** [comment]
win10  64位专业版   终端是babun
具体的教程是按照这个来的：http://www.jianshu.com/p/95353caba441


来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：PeterDing <notifications@github.com>
时间：周三 9月7日 上午 10:07
收件人：PeterDing/iScript <iScript@noreply.github.com>
抄送：Lugic1993 <tdstevelx333@outlook.com>,Author <author@noreply.github.com>
主题：Re: [PeterDing/iScript] win10 Tumblr.py 报错提示 (#85)

**Comment by Lugic1993** [comment]
请问具体会是什么原因呢？求教
