### ISSUE TITLE
pan.baidu.com.py获取share报错

### ISSUE THREAD

**Issue by jumpx1** [PeterDing/iScript#89]
你好，

pan.baidu.com.py获取百度网盘share报错，貌似百度云盘API的结构又有变化了。。。

Traceback (most recent call last):
  File "pan.baidu.com.py", line 3715, in <module>
    main(argv)
  File "pan.baidu.com.py", line 3711, in main
    handle_command(comd, xxx)
  File "pan.baidu.com.py", line 3424, in handle_command
    x.save_share(url, remotepath, infos=infos)
  File "pan.baidu.com.py", line 1617, in save_share
    infos = self._get_share_infos(url, remotepath, infos)
  File "pan.baidu.com.py", line 1581, in _get_share_infos
    info = panbaiducom.get_web_fileinfo(html, url)
  File "pan.baidu.com.py", line 3011, in get_web_fileinfo
    info['bdstoken']  = re.search(r'yunData.MYBDSTOKEN = "(.*?)"', cm).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):

没有“bdstoken"这个。。。

**Comment by PeterDing** [comment]
好像是，稍等，我修正一下

**Comment by jumpx1** [comment]
谢谢，静等老大修复。。。

**Comment by PeterDing** [comment]
修复了保持分享和删除文件

试试～

**Comment by jumpx1** [comment]
bp save http://pan.baidu.com/s/1kU5Xw3t 123
  请输入提取密码: 5nse
  !! 提取密码错误

好像还有问题啊。

**Comment by jumpx1** [comment]
??没有人看看么，谢谢

**Comment by PeterDing** [comment]
再试试，看看还有问题吗

**Comment by jumpx1** [comment]
好了，谢谢！
