### ISSUE TITLE
Tumblr.py with GDrive

### ISSUE THREAD

**Issue by TMily** [PeterDing/iScript#93]
我在VPS上挂载GoogleDrive为本地磁盘然后尝试直接将Tumblr爬到GDrive上。但是脚本似乎不太适应这种低IO的虚拟磁盘直接报错了
IOError: [Errno 16] Device or resource busy
而如果是用Wget直接下载文件的话完全正常

**Comment by qinwf** [comment]
GDrive 挂载的方式一般是不支持 seek 的，比如用 rclone 挂载，就不能用多线程下载，其他挂载同理，需要顺序写入。可以先写到实体硬盘里，再移动到 GDrive。

**Comment by TMily** [comment]
我尝试过p=1 也还是不行呢？或者能不能加个开关调用wget？ 毕竟wget是可以的。先写到本地硬盘可以是可以，可是我的VPS硬盘只有几个GB，如果爬视频的话不一定够，还得中断移动再指定offset，我用的是fuse挂载。

**Comment by PeterDing** [comment]
tumblr.py 是用 wget 下载的，见：

https://github.com/PeterDing/iScript/blob/master/tumblr.py#L122

我没有用过 gdrive 挂载的方式，如果这种方式不支持 seek，可以试试把
[123行](https://github.com/PeterDing/iScript/blob/master/tumblr.py#L123) 中的 `'-c'` 去掉，但这样就不能断点下载了，出错的文件需要手动删掉。

**Comment by TMily** [comment]
谢作者答，不过去掉-c之后还是报错，是否还有其他参数会产生影响？

**Comment by TMily** [comment]
我贴一下详细的Traceback 吧
`Traceback (most recent call last):
  File "/root/iScript/tumblr.py", line 617, in <module>
    main(argv)
  File "/root/iScript/tumblr.py", line 578, in main
    items = tumblr.get_item_generator()
  File "/root/iScript/tumblr.py", line 479, in get_item_generator
    items = self.make_items()
  File "/root/iScript/tumblr.py", line 377, in do
    self.save_json()
  File "/root/iScript/tumblr.py", line 292, in save_json
    {'offset': self.offset}, indent=4, sort_keys=True))
IOError: [Errno 16] Device or resource busy`

**Comment by TMily** [comment]
换用RClone 挂载之后正常上传下载，看来是因为AUR中的包版本过旧造成的 关闭
