### ISSUE TITLE
百度音乐FLAC下载失效，并部分歌手搜索出错

### ISSUE THREAD

**Issue by macdavis** [PeterDing/iScript#94]
OS: macOS 10.12.2 (16C67) 

运行`python music.baidu.com.py http://music.baidu.com/song/117948039 -f`

抓到的却是mp3的地址
`URL:http://yinyueshiting.baidu.com/data2/music/e27fc0530f4a014d62ce2d42c1f56073/125590384/11794803954000128.mp3?xcode=97f8c89670f9e69035dc224202a6daff [4626309/4626309] `

并且运行`python music.baidu.com.py http://music.baidu.com/album/288364131 -f`会报错，提示

Traceback (most recent call last):
  File "music.baidu.com.py", line 247, in <module>
    main(args.url)
  File "music.baidu.com.py", line 236, in main
    x.url_parser()
  File "music.baidu.com.py", line 121, in url_parser
    self.get_album_infos()
  File "music.baidu.com.py", line 169, in get_album_infos
    d = modificate_text(self.song_infos[0]['album_name'] + ' - ' + self.song_infos[0]['artist_name'])
IndexError: list index out of range

同样，运行`python music.baidu.com.py http://music.baidu.com/song/288364202 -f`报错，

Traceback (most recent call last):
  File "music.baidu.com.py", line 247, in <module>
    main(args.url)
  File "music.baidu.com.py", line 236, in main
    x.url_parser()
  File "music.baidu.com.py", line 125, in url_parser
    self.get_song_infos()
  File "music.baidu.com.py", line 133, in get_song_infos
    song_info['song_id'] = unicode(j['data']['songList'][0]['songId'])
IndexError: string index out of range

**Comment by PeterDing** [comment]
很长时间没有更新脚本了，一定会出错的。。。
等我更新一下吧
