### ISSUE TITLE
pan.baidu.com.py 登录失败

### ISSUE THREAD

**Issue by ShekBoy** [PeterDing/iScript#96]
bp login
/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
  username: email@gmail.com
  password:

  -- login
Traceback (most recent call last):
  File "/root/iScript/pan.baidu.com.py", line 3592, in <module>
    main(argv)
  File "/root/iScript/pan.baidu.com.py", line 3588, in main
    handle_command(comd, xxx)
  File "/root/iScript/pan.baidu.com.py", line 3124, in handle_command
    xh.login(username, password)
  File "/root/iScript/pan.baidu.com.py", line 365, in login
    'login')
  File "/root/iScript/pan.baidu.com.py", line 248, in _request
    response = ss.request(method, url, **kwargs)
  File "/root/iScript/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/iScript/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/root/iScript/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'passport.baidu.com' doesn't match u'baidu.com'

另外想请问头四行的错误是我弄错还是弄漏了啥吗？

**Comment by PeterDing** [comment]
requests 报错，试试把 requests 删除后再重装

**Comment by ShekBoy** [comment]
感谢，把requests换回2.6.0就好了
