### ISSUE TITLE
使用aget下载百度云大文件有时会卡住

### ISSUE THREAD

**Issue by nujabse** [PeterDing/iScript#99]
错误代码：
`Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
  File "/usr/lib/python3.5/site-packages/aget/download.py", line 103, in save_data
  File "/usr/lib/python3.5/site-packages/aget/models.py", line 62, in record_data
  File "/usr/lib/python3.5/site-packages/aget/models.py", line 121, in write
OSError: [Errno 24] Too many open files: `

**Comment by PeterDing** [comment]
`Too many open files` 表示系统的文件描述符 (descriptors) 用光了。

你可以用 `ulimit -a | grep descriptors` 查看文件描述符数量。

如果你有 root 权限，你可以用 `ulimit -n Num` 来增加文件描述符数量。
